---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site-vitrine-loutik
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/site-vitrine-loutik
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-manifests
  targetNamespace: site-internet
